name: Performance Tests

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  k6-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install k6
        run: |
          sudo gpg -k
          sudo gpg --no-default-keyring --keyring /usr/share/keyrings/k6-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install k6

      - name: Clean Old Content
        run: |
            rm -rf public/*          

      - name: Run k6 test
        run: |
          mkdir -p ./logs
          k6 run tests/login.js

      - name: Upload k6 results
        uses: actions/upload-artifact@v4
        with:
          name: k6-results
          path: logs/

  deploy:
    name: Deploy GitHub Pages 🌐
    runs-on: ubuntu-latest
    needs: 
    - k6-tests
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: https://marilliadantas.github.io/serverest-test-k6/report.html
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with: 
        name: k6-results

    - name: Setup Pages
      uses: actions/configure-pages@v5

    - name: Upload Pages Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4